### ISSUE TITLE
Increase code coverage (2)

### ISSUE THREAD

**Issue by massdosage** [HotelsDotCom/waggle-dance#100]
_As a developer_
_I'd like to be confident my tests can detect refactoring issues_
_So I can easily make code changes_

**Acceptance criteria**
Code coverage should be at least 80%

Below is a list of classes which could benefit from some extra testing and should be the focus of this ticket. They are arranged (more or less) in increasing test complexity:

ValidationError
FederatedMetaStore
PrimaryMetaStore
MetastoreUnavailableException
TunnelableFactorySupplier
TunnelingMetaStoreClientFactory
NotifyingFederationService
AdvancedPropertyUtils

PrefixBasedDatabaseMappingService
WaggleDanceConfiguration
YamlStorageConfiguration (trivial)
MonitoringConfiguration

FederatedHMSHandlerFactory
FederatedHMSHandler

**Comment by AnanaMJ** [comment]
@massdosage ValidationError test PR: https://github.com/HotelsDotCom/waggle-dance/pull/104

**Comment by AnanaMJ** [comment]
@massdosage I updated #104 with the tests for FederatedMetaStore and PrimaryMetaStore.

**Comment by AnanaMJ** [comment]
@massdosage Thank you for the feedback so far! 
I added a test to NotifyingFederationService to get 100% coverage, but I will need to continue on Thursday (or later today) with TunnelingMetaStoreClientFactory because there are some private and final classes that can't be mocked with the current configuration. I'll spend more time with it and try different strategies and hopefully I can get that to 100% 😄

**Comment by AnanaMJ** [comment]
@courtsVII I updated #104 with the tests for TunnelingMetaStoreClientFactory :)

**Comment by AnanaMJ** [comment]
@massdosage I added tests for AdvancedPropertyUtils and PrefixBasedDatabaseMappingService but they're not at 100% coverage because some of the cases are not testable (unmockable or defensive programming code).
There are also now tests for WaggleDanceConfiguration and YamlStorageConfiguration :)

**Comment by AnanaMJ** [comment]
FederatedHMSHandler will not have any tests added for this issue. The tests that are not covered will be added as part of another issue.
