### ISSUE TITLE
Refactor duplicated SSH code

### ISSUE THREAD

**Issue by massdosage** [HotelsDotCom/waggle-dance#103]
_As a developer
I want code that is duplicated by code present in [hcommon-ssh](https://github.com/HotelsDotCom/hcommon-ssh/) removed from WaggleDance
So that I have less code to maintain, can fix bugs in one place etc._

**Acceptance Criteria**
The following are candidates for refactoring, further investigation might reveal that it's not feasible so for all of the below we should either make the change or document why we decided not to:
- Replace `com.hotels.bdp.waggledance.api.model.MetastoreTunnel` with `com.hotels.hcommon.ssh.SshSettings`
- If the above is successful create a similar ticket to this for [CircusTrain](https://github.com/HotelsDotCom/circus-train) to make the same change for `com.hotels.bdp.circustrain.api.conf.MetastoreTunnel`
- Replace `com.hotels.bdp.waggledance.api.validation.constraint.TunnelRoute` with `com.hotels.hcommon.ssh.validation.constraint.TunnelRoute` and
`com.hotels.bdp.waggledance.api.validation.validator.TunnelRouteValidator` with `com.hotels.hcommon.ssh.validation.validator.TunnelRouteValidator`
- If the above is successful create a similar ticket to this for [CircusTrain](https://github.com/HotelsDotCom/circus-train) to make the same change for `com.hotels.bdp.circustrain.api.validation.constraints.TunnelRoute` and `com.hotels.bdp.circustrain.api.validation.constraintvalidators.TunnelRouteValidator`)
- Look at `TunnelableFactorySupplier` and how we're using `WaggleDanceHiveConfVars`, could we replace some of this with `com.hotels.hcommon.ssh.SshSettings` or `com.hotels.hcommon.hive.metastore.client.tunnelling.TunnellingMetaStoreClientSupplierBuilder`? See https://github.com/HotelsDotCom/circus-train/commit/0272e36281bc70034c50d27a5822e160d80f3bc9 for a similar change to CircusTrain that could possibly be applied here.
- Check whether is any scope for refactoring/removing any code in `com.hotels.bdp.waggledance.client.TunnelingMetaStoreClientFactory`
- Above code tested out in our development environment in AWS via a tunnel to ensure tunnels still work correctly.

**Comment by AnanaMJ** [comment]
@massdosage There is a `MetastoreTunnel` that seems to be like the one in WaggleDance in Housekeeping as well: https://github.com/HotelsDotCom/housekeeping/blob/master/housekeeping-vacuum-tool/src/main/java/com/hotels/housekeeping/tool/vacuum/conf/MetastoreTunnel.java

Should I refactor Housekeeping too if the WaggleDance and CircusTrain refactoring works well?

**Comment by massdosage** [comment]
Yes please.
