### ISSUE TITLE
Performance degradation on tunneled connection

### ISSUE THREAD

**Issue by bAndie91** [HotelsDotCom/waggle-dance#115]
I've experienced performance degradation when upgraded from 2.2.2 to 2.3.7. 
see measurements in attachment which was made by Spark application calling `spark.catalog.listTables()`.
newer WD is 3 times slower impacting the ssh-tunneled connections (see highlighted rows) the most.
![image](https://user-images.githubusercontent.com/802732/43392117-f3039f6c-93f2-11e8-92f6-a2949869629e.png)

how much can it be eliminated?

**Comment by rambrus** [comment]
@bAndie91 , @patduin: I did some investigation and found this:

**Test Case 1 - listTables on non-tunneled connection**

wd version | run-1 | run-2
-- | -- | --
2.3.0 | 20 s | 19 s
2.3.1 | 20 s | 23 s
2.3.2 | 25 s | 24 s
2.3.3 | 36 s | 32 s
2.3.4 | 28 s | 25 s
2.3.5 | 44 s | 56 s
2.3.6 | 48 s | 46 s

![image](https://user-images.githubusercontent.com/10614761/43522358-664fa04a-9599-11e8-8198-06e626fa6ead.png)

**Test Case 2 - listTables on tunneled connection**

wd version | run-1 | run-2
-- | -- | --
2.3.0 | 5 m 37 s | 4 m 52 s
2.3.1 | 4 m 59 s | 5 m 04 s
2.3.2 | 5 m 15 s | 5 m 11 s
2.3.3 | 7 m 27 s | 7 m 12 s
2.3.4 | 5 m 14 s | 5 m 15 s
2.3.5 | 13 m 02 s | 13 m 27 s
2.3.6 | 12 m 33 s | 13 m 07 s

![image](https://user-images.githubusercontent.com/10614761/43522404-8d9ad340-9599-11e8-94af-cd90e1025a52.png)

**Summary**
I had 2 runs for both test cases, the test durations are pretty much consistent between runs and we can observe ~150% performance degradation between 2.3.4 and 2.3.5 releases.

IMPORTANT: The performance degradation does not seem to be specific to *tunneled connection*, the same trend can be observed in both cases.

**Comment by patduin** [comment]
Excellent work! 
Got one more questions in your WD configuration are all metastores reachable and responding or is one of them down?

**Comment by rambrus** [comment]
@bAndie91 can you please answer the question above?

I also checked the spark logs if they can contain any unusual error.
I have seen this error many times in the logs starting from v2.3.3:
![image](https://user-images.githubusercontent.com/10614761/43525532-5b870a96-95a2-11e8-8509-ca5c330521be.png)

This might be also interesting.

**Comment by patduin** [comment]
I think I know what is going on. A change I made related to #73 . Does an extra call to verify the connection is open.

**Comment by patduin** [comment]
Can I ask you to try and build/run this branch: https://github.com/HotelsDotCom/waggle-dance/tree/issue-115
I suspect the changed line is what is causing the issue or at least I want to rule this out. 
I'll also make an internal ticket for us to setup performance tests as we should be catching these issues. Apologies for that.

**Comment by rambrus** [comment]
@patduin Sure, will check that branch and get back to you with the results.

**Comment by bAndie91** [comment]
@patduin all the metastore connections are AVAILABLE during the tests run.

**Comment by patduin** [comment]
ok thanks really helpful! We'll need to find some other way to fix #73 without introducing the performance hit. Not sure yet how but at least we know what is going on :)

**Comment by rambrus** [comment]
cheers, let us know when the fix is available, we are happy to take a quick look at the performance.

**Comment by patduin** [comment]
Will do and thanks!

**Comment by rambrus** [comment]
@patduin sure, will take a look and get back to you with results.

**Comment by rambrus** [comment]
@patduin : test executed on [4791baf](https://github.com/HotelsDotCom/waggle-dance/pull/118/commits/4791baf6ea05772697422f433855a4cfe8bddbe8) and added the result to the chart.

![image](https://user-images.githubusercontent.com/10614761/43959140-1a598b4e-9cae-11e8-93f9-80855af508e2.png)

![image](https://user-images.githubusercontent.com/10614761/43959148-266aad6e-9cae-11e8-96b4-4e193dea71c1.png)

I can see some performance degradation in both cases, but it's not so critical than in v2.3.5.

**Comment by patduin** [comment]
yeah I can't really account for that. We merged the PR with the changes and try to make a release this week.

**Comment by patduin** [comment]
This is adressed in 2.4.2 release, if the performance is still an issue please reopen or open a new ticket, closing this.
