### ISSUE TITLE
How do Filters, Sorting, Joins, and Merges work with Waggle Dance

### ISSUE THREAD

**Issue by rajeshsaluja** [HotelsDotCom/waggle-dance#121]
I've question on Filter, Sorting, Joins, Merge through waggle-dance

E.g. `select * from remotedb.emp where created_date > sysdate - 365` through waggle-dance (`emp` table exists in remote hive metastore)

Does above statement does filter at remote metastore and then waggle dance get the data or entire table data is pulled before applying filter condition.

Similar question for sorting or joins of tables across metastore. Where does the actual operation is carried out.

Thanks

**Comment by patduin** [comment]
Waggle Dance only interacts with hive on the metadata level. So all actual data manipulation is done on the cluster from which you fire you're query.

**Comment by rajeshsaluja** [comment]
Great . Thanks on the clarification !

**Comment by rajeshsaluja** [comment]
We are doing experimentation across regions with one of the region in our own data center and other in AWS.
