### ISSUE TITLE
Qubole Notebook not showing federation databases

### ISSUE THREAD

**Issue by ambrish29** [HotelsDotCom/waggle-dance#135]
When running following set of command via hive or spark engine on Qubole, proper results are displayed. i.e.  List of all the databases from primary & federated MSs are showing.

```
hive> show databases;
LIST_OF_PRIMARY_MS_SCHEMAS
LIST_OF_FEDERATED_MS_SCHEMAS
```

When running same query via qubole-notebook, only PM schemas are displayed. I am using same Spark cluster.

```
spark.sql("show databases").show()
ONLY_LIST_OF_PRIMARY_MS_SCHEMAS
```

**Comment by patduin** [comment]
That to me looks like the spark query is not using WD. Can you check the `hive.metastore.uris` property and confirm it is the thrift uri for Waggle Dance?

**Comment by ambrish29** [comment]
I will check this.

Since `hive.metastore.uris` is configured at cluster level and if I am using same cluster in notebook then it should work out of the box unless notebook is overwriting this property.

**Comment by massdosage** [comment]
We've had lots of fun and games with Hive settings being changed within Qubole and also within Spark itself. Let us know what you find, we can then check what teams on our side have done to get this working in our equivalent environments.

**Comment by ambrish29** [comment]
I ran following command on Qubole notebook
```
spark.sql("set hive.metastore.uris").show()
```

And it returned following result:

```
+-------------------+-----------+
|                key|      value|
+-------------------+-----------+
|hive.metastore.uris|<undefined>|
+-------------------+-----------+
```

So looks like notebook is overwriting (atleast) this property.

**Comment by ambrish29** [comment]
UPDATE

I changed updated this property using following command:

```
spark.sql("set hive.metastore.uris=thrift://waggle-dance:12345")
```

And executed the same command and no success. I am still getting same results.

**Comment by ambrish29** [comment]
UPDATE

Using following property solved the issue:

```
spark.hadoop.hive.metastore.uris thrift://waggle-dance:12345
```

Navigation
`Clusters > [EDIT specific Spark Cluster] > Advance Configuration > SPARK SETTINGS`

**Comment by massdosage** [comment]
Thanks for the extra info on resolving the issue!

**Comment by ambrish29** [comment]
May be adding this info in the README should be helpful to everyone.

**Comment by massdosage** [comment]
Yeah, I'm not sure, it should really be documented in Spark/Qubole - "How to specify a custom Hive metastore" as it's not really related to WaggleDance directly. If we add it to our documentation then we have the maintenance burden of keeping this up to date for different versions of Qubole/Spark etc.
