### ISSUE TITLE
add_foreign_key and add_primary_key methods in FederatedHMSHandler don't use specified DB to federate to correct metastore

### ISSUE THREAD

**Issue by patduin** [HotelsDotCom/waggle-dance#137]
In the FederatedHMSHandler class we have implemented add_foreign_key and add_primary_key, but those calls are proxied to the primary metastore. The argument in both methods have a db name so we should be able to proxy this correctly.

Acceptance Criteria:

* add_foreign_key proxies to correct metastore.
* add_primary_key proxies to correct metastore.

**Comment by AnanaMJ** [comment]
I couldn't find a way to get the database for those functions. `add_foreign_key` receives a `AddForeignKeyRequest` object, which doesn't expose any methods for getting the database. Same for `add_primary_key`; it receives an `AddPrimaryKeyRequest` object.

**Comment by patduin** [comment]
you're right only the `get` methods seem to have it. ok closing this. Thanks for checking!
