### ISSUE TITLE
Allow primary metastore to have a prefix

### ISSUE THREAD

**Issue by AnanaMJ** [HotelsDotCom/waggle-dance#152]
_As a user_
_I'd like to be able to set `primary_metastore.database-prefix` in the configuration without it being replaced by empty string_
_So that I can apply consistent prefixes across multiple waggle dance instances having different primary and federated metastores and thus re-use the same queries regardless of which waggle dance instance I am connected to._

**Comment by massdosage** [comment]
Depending on what we do for https://github.com/HotelsDotCom/waggle-dance/issues/154 this might be resolved at the same time but it could also be worth doing sooner as this is already a feature that would be useful in Apiary.
