### ISSUE TITLE
BitSetCheckedAuthorizationProvider#authorizeUserPriv without DbName  cannot contact to waggle-dance

### ISSUE THREAD

**Issue by Elvis0607** [HotelsDotCom/waggle-dance#158]
when using BitSetCheckedAuthorizationProvider to do authorization, the dbname is null. Waggle dance cannot process the request.

protected boolean authorizeUserPriv(Privilege[] inputRequiredPriv,
      boolean[] inputCheck, Privilege[] outputRequiredPriv,
      boolean[] outputCheck) throws HiveException {
    PrincipalPrivilegeSet privileges = hive_db.get_privilege_set(
        HiveObjectType.GLOBAL, null, null, null, null, this.getAuthenticator()
            .getUserName(), this.getAuthenticator().getGroupNames());
    return authorizePrivileges(privileges, inputRequiredPriv, inputCheck,
        outputRequiredPriv, outputCheck);
  }

I think waggle dance can change to 

public PrincipalPrivilegeSet get_privilege_set(HiveObjectRef hiveObject, String user_name, List<String> group_names)
    throws MetaException, TException {
    DatabaseMapping mapping;

    if(hiveObject.getDbName().equals(null)){
      mapping = databaseMappingService.primaryDatabaseMapping();
    }else{
      mapping = databaseMappingService.databaseMapping(hiveObject.getDbName());
    }

    return mapping.getClient().get_privilege_set(mapping.transformInboundHiveObjectRef(hiveObject), user_name,
        group_names);
  }

**Comment by patduin** [comment]
That sounds like a good plan, would you consider contributing a PR for this?

**Comment by massdosage** [comment]
Sounds reasonable, a PR would be fantastic, ideally with a unit test to cover this if possible.

**Comment by Elvis0607** [comment]
I have no experience to make an effort for open-source project. After testing it well, I will try to contribute a PR.

I have just tested like this: 

    DatabaseMapping mapping;
    HiveObjectRef hiveObjectResult;
    if(hiveObject.getDbName() == null){
      mapping = databaseMappingService.primaryDatabaseMapping();
      hiveObjectResult = hiveObject;
    }else{
      mapping = databaseMappingService.databaseMapping(hiveObject.getDbName());
      hiveObjectResult = mapping.transformInboundHiveObjectRef(hiveObject);

    }
    return mapping.getClient().get_privilege_set(hiveObjectResult, user_name,
            group_names);


It can work.
