### ISSUE TITLE
Purpose of CommonVFSResource

### ISSUE THREAD

**Issue by chergey** [HotelsDotCom/waggle-dance#178]
Hi, 
There is a class (com.hotels.bdp.waggledance.spring.CommonVFSResource) that I can't find usages of, nor how it is instantiated. If it is not used, I think, it can be removed (partly because CommonVFSResourceTest fails on Windows machine).

**Comment by patduin** [comment]
Good question, we'll have a look at this. Thanks for reporting!

**Comment by patduin** [comment]
I think you are right, I've created a PR to remove the class and test.
