### ISSUE TITLE
Allowing federated metastores to take on an empty string for prefix

### ISSUE THREAD

**Issue by DewinGoh** [HotelsDotCom/waggle-dance#183]
**Is your feature request related to a problem? Please describe.**
I am trying to have a pre-prod setup for my spark scripts - they are supposed to read from prod storage and write to pre-prod storage. Hence, I want to have the federated metastore point to my prod, and primary metastore pointing to my pre-prod. To minimize code change required in the spark scripts, I want to call the databases as they are in prod, but the configuration does not allow me to leave the federated metastore prefix empty.

**Describe the solution you'd like**
I'd like to be able to leave the federated metastore prefix as an empty string for at least one metastore. Perhaps this could be done by just doing a check on all prefixes and approving them as long as they are unique, rather than hardcoding a standard.

**Describe alternatives you've considered**
No working alternatives to this issue.

**Comment by patduin** [comment]
Perhaps setting `database-resolution: MANUAL` might be a workaround. It allows no prefixes anywhere but you have to specify which db should be federated to to prevent naming collisions.

**Comment by DewinGoh** [comment]
I'd still prefer to form prefixes on all of the primary metastore's databases for simplicity

**Comment by AnanaMJ** [comment]
Hi @DewinGoh, just so I make sure I understand this correctly - you would like the option to have a federated metastore with an empty prefix.
Would you want the primary metastore to also have an empty prefix?
And all prefixes for federated metastores would be unique, right?

**Comment by DewinGoh** [comment]
hi @AnanaMJ , partly correct - I would like to have the option to set ONE of the metastores, be it federated or not, with an empty prefix. Simply put, there can still only be one metastore with an empty prefix, but it should not be just limited to the primary metastore.

**Comment by massdosage** [comment]
This has been released in Waggle Dance 3.5.0.
