### ISSUE TITLE
JMX metrics documentation

### ISSUE THREAD

**Issue by DewinGoh** [HotelsDotCom/waggle-dance#187]
Hi, I'm trying to observe the metrics of this service through JMX, but it is not really well documented, and the usual configurations for jmx to attach to java processes such as https://stackoverflow.com/questions/35466461/how-to-connect-with-jmx-from-host-to-docker-container-in-docker-machine are not really working. 

Could I get a sample of how JMX metrics are to be exposed for WaggleDance? Is it on the /metrics endpoint, what must be specifically passed into the JAVA_OPTS? 

Many thanks

**Comment by massdosage** [comment]
Have you tried using the standard Spring boot metrics endpoints? See https://github.com/HotelsDotCom/waggle-dance/#endpoints

I don't think you need to do anything specific to enable them, they should just be there by default...

**Comment by DewinGoh** [comment]
Just explored them - the HTTP endpoints are definitely available, but still having some trouble with the JMX ones. If you have a working set up to extract the JMX metrics remotely, would be great if you could share it...

Also, in which yml file are we recommended to configure the types of HTTP endpoints exposed?

**Comment by massdosage** [comment]
I think this is all controlled by the Spring boot actuator so you should be able to pass in arguments when starting WaggleDance to enable/disable and further configure the endpoints. You may be able to do this in 

https://github.com/HotelsDotCom/waggle-dance/blob/master/waggle-dance/src/main/scripts/waggle-dance.sh

(this will be in the bin folder of the WaggleDance .tgz)

or by altering the RUN_ARGS that get passed to the Spring Boot service:

https://github.com/HotelsDotCom/waggle-dance/blob/master/waggle-dance/src/main/service/waggle-dance.conf

(this will be in the service folder of the WaggleDance .tgz)

I don't have any examples that I'm aware of showing how to get JMX out directly but reading through the Spring Boot and Actuator documentation it looks like you should be able to do it by passing through some configuration values.

**Comment by DewinGoh** [comment]
Thanks for the pointers - managed to retrieve the JMX metrics by putting "--spring.jmx.enabled=true" in RUN_ARGS and passing some values into JAVA_OPTS.

**Comment by massdosage** [comment]
Great, thanks for letting us know.
