### ISSUE TITLE
Metastores should support "mapped-tables" similar to "mapped-databases"

### ISSUE THREAD

**Issue by barnharts4** [HotelsDotCom/waggle-dance#195]
**Is your feature request related to a problem? Please describe.**
When federating certain metastores, I need a way to only expose certain tables from certain schemas in the metastore.

**Describe the solution you'd like**
I would like a configuration parameter like `mapped-tables` or `mapped-db-tables` that would work similar to `mapped-databases` (or supersede `mapped-databases`) that would allow Regexs to be used to specify a combination of mapped schemas and tables from the schemas.

**Describe alternatives you've considered**
 Currently we are managing this with Apache Ranger policies to only allow access to certain tables in the schemas we are federating.  However, the downside to this is that they are still visible, leading customer to try to query them, and Ranger policies can be somewhat complex to create if they span multiple schemas/tables/users.

**Comment by andreeapad** [comment]
Released in Waggle Dance 3.8.0
