### ISSUE TITLE
Add integration test for federations over SSL

### ISSUE THREAD

**Issue by ddcprg** [HotelsDotCom/waggle-dance#23]
_As a developer_
_I'd like to test that SSL connectivity_
_So I can make sure that federations over SSL works the same as federations over plain connectivity_

**Acceptance Criteria**
New integration test that federates megastores over SSL

Note: this we'll depend on [BeeJU ticket 8](https://github.com/HotelsDotCom/beeju/issues/8)

**Comment by massdosage** [comment]
Closing for now as we haven't (yet) received any requests for SSL support.
