### ISSUE TITLE
Increase code coverage (1)

### ISSUE THREAD

**Issue by ddcprg** [HotelsDotCom/waggle-dance#25]
_As a developer_
_I'd like to be confident my tests can detect refactoring issues_
_So I can easily make code changes_

**Acceptance criteria**
Code coverage should be at least 80%

Below is a list of classes which could benefit from some extra testing and should be the focus of this ticket. They are arranged (more or less) in increasing test complexity:

WaggleDanceException
AbstractMetaStore
Federations
CloseableThriftHiveMetastoreIfaceClientFactory
GrammarUtils
MonitoredDatabaseMappingService
AccessControlHandlerFactory

GraphiteConfiguration

StaticDatabaseMappingService
CommonVFSResource

TunnelingMetaStoreClientFactory
WaggleDanceRunner -> could at least test the builder part of this
DefaultMetaStoreClientFactory
ThriftMetastoreClient

**Comment by massdosage** [comment]
Some additional comments from @ddcprg received via e-mail:

> The initial list of classes which can be added/extended (or removed?) to improve coverage:
>  
>     GraphiteConfiguration
>     WaggleDanceConfiguration
>     YamlStorageConfiguration
>     CommonVFSResource
>     Replace tunneling classes with the ones in common-ssh -> this should help to bump the coverage
>     MonitoringConfiguration -> probably needs to be a SpringTest
>     TunnelingMetaStoreClientFactory -> there are untested branches
>     FederatedHMSHandler -> seems can be 100% tested, depends on how much time we want to spend on this, 100% coverage here may be important
>     FederatedHMSHandlerFactory -> there are untested branches
> 
> The first 3 are just configuration objects which I think should be tested for validations and would help to understand the configuration details of WD.
>  
> Anything else not on the list is probably better to be covered with integration test since unit test would be hard to figure out. I think we already have some and the framework may not be properly reporting coverage for those.

**Comment by massdosage** [comment]
Below is a list of classes which could benefit from some extra testing and should be the focus of this ticket. They are arranged (more or less) in increasing test complexity:

WaggleDanceException
AbstractMetaStore
Federations
CloseableThriftHiveMetastoreIfaceClientFactory
GrammarUtils
MonitoredDatabaseMappingService
AccessControlHandlerFactory

GraphiteConfiguration

StaticDatabaseMappingService
CommonVFSResource

TunnelingMetaStoreClientFactory
WaggleDanceRunner -> could at least test the builder part of this
ThriftMetastoreClient

**Comment by AnanaMJ** [comment]
@andreeapad TunnelingMetaStoreClientFactory is done from my side ;)

**Comment by andreeapad** [comment]
Fixed by #114
