### ISSUE TITLE
tunneling: Support multiple host key encyptions

### ISSUE THREAD

**Issue by patduin** [HotelsDotCom/waggle-dance#32]
_As a user of Waggle Dance
I'd like to have a working tunnel where my host key is of any encryption type
So that I can seamlessly create tunnels on newer SSH installations_

We've seen the JCSH library we use for tunneling fail with `Caused by: com.jcraft.jsch.JSchException: UnknownHostKey` on host checks when the `.ssh/known_hosts` file has keys encrypted with `ecdsa-sha2-nistp256`. 

### Acceptance Criteria:
* Investigate if we can make JCSH work with all encryptions

### Work around
A command line workaround is to get the RSA key using `ssh-keyscan host-ip` and adding that to the known_hosts file:

    ssh-keyscan <host-ip> >> .ssh/known_hosts

**Comment by courtsVII** [comment]
`metastore-tunnel.strict-host-key-checking` feature added
