### ISSUE TITLE
tunneling: Make strict host checking optional

### ISSUE THREAD

**Issue by patduin** [HotelsDotCom/waggle-dance#33]
_As a user of Waggle Dance
I'd like to make strict host checking option
So that I can bypass any host checking issues_

The JSCH library we use to setup the ssh tunnel can be configure to skip strict host checking. We ran into issue (see https://github.com/HotelsDotCom/waggle-dance/issues/32) where the encryption key wasn't supported and it would be great to have quick workarounds for this. Or at least leave it up to the user to enable or disable strict host checking.

Acceptance Criteria
* configuration flag in the yaml to disable/enable strict host checking per tunnel.

**Comment by courtsVII** [comment]
`metastore-tunnel.strict-host-key-checking` feature added
