### ISSUE TITLE
Configure and use the HADOOP_USER_NAME in WD for all requests

### ISSUE THREAD

**Issue by patduin** [HotelsDotCom/waggle-dance#40]
_As a user of WD_
_I'd like to issue all requests to a federated metastore as one user_
_So that I can implement authorization for that one user and not for all clients_

## Acceptance Criteria:

* Waggle Dance configuration allows configuration for HADOOP_USER_NAME (Decide on property name, decide for all metastores or per metastore configuration?)
* If the HADOOP_USER_NAME is set in the WD configuration then it is used and overrides any client set username.

Example my hive cli client issues all requests as user 'hadoop'. If the WD HADOOP_USER_NAME is set then the user 'hadoop' is ignored and whatever value WD is configured with is used instead.

### Notes
Might help with what is discussed in https://groups.google.com/d/msg/waggle-dance-user/rA3JPimh94A/0q0ZXasjAwAJ

**Comment by massdosage** [comment]
@patduin is this worth keeping open?

**Comment by patduin** [comment]
No let's close it never had a request for this.
