### ISSUE TITLE
Persist config file during process restart

### ISSUE THREAD

**Issue by pradeepbhadani** [HotelsDotCom/waggle-dance#44]
_As a SysOps_
_I want WD to avoid overwriting local config during process restart_
_So that I do not lose local configs_

Acceptance Criteria:
* WD to not update/re-write config file during restart

**Comment by courtsVII** [comment]
This is supported by adding
`yaml-storage:
    overwrite-config-on-shutdown: true`
to your waggle-dance-server.yml config
