### ISSUE TITLE
Add generic whitelisting feature for every metastore mappings

### ISSUE THREAD

**Issue by ddcprg** [HotelsDotCom/waggle-dance#59]
At the moment the whitelisting logic is spread across the different services and it feels like these checks could be done just before the request hits the handler.

We would like to centralize the whitelisting logic in one place and make sure all requests go through the checks before they are processed. These should also simplify the mapping services.

**Comment by massdosage** [comment]
Centralising the whitelisting code would also make it more consistent - i.e. in some places now we use regular expressions and in other we do string matching. Hopefully everything can be made to use regular expressions which thus would increase consistency in how we do things and offer more functionality to end users.

**Comment by massdosage** [comment]
Closing for now, we can re-open if/when we work on something that touches this area of code.
