### ISSUE TITLE
Use configuration-properties in clients HiveConf

### ISSUE THREAD

**Issue by patduin** [HotelsDotCom/waggle-dance#77]
_I'd like to use the `configuration-properties` that I can set in the `waggle-dance-server.yml` in HiveConf that is used to create Thrift Clients._

Currently we use the properties only in the Handler (the server), it would be good if we can set properties and override settings used in the clients. 
For instance see `ThriftMetastoreClient` it contains this code:
`    retries = HiveConf.getIntVar(conf, HiveConf.ConfVars.METASTORETHRIFTCONNECTIONRETRIES);
`
But there is currently no way to override this cause we create the HiveConf ourselves in `CloseableThriftHiveMetastoreIfaceClientFactory`. Thus that values is hardcoded to the Hive default  3.

### Acceptance Criteria:

- Use the`configuration-properties`(see `WaggleDanceConfiguration` class) when creating the HiveConf for the clients.
- Documents it's use in the README (it seems to be a hidden feature now).

**Comment by courtsVII** [comment]
#90 Waggle Dance Glue PR adds this feature

**Comment by AnanaMJ** [comment]
Hey @patduin , would this look something like this? https://github.com/HotelsDotCom/waggle-dance/compare/issue-77?

**Comment by massdosage** [comment]
@patduin is this worth keeping open? Is the above PR from @AnanaMJ something we want to merge?

**Comment by patduin** [comment]
maybe keep this one as it might have a fix already. We just need to check backward compatiblity/implications. etc...
